#!/bin/bash
#coded by AwesomeGuyPrince
#kalian
figlet -f slant 'KALIAN' | lolcat && figlet -f digital  " Coded by AwesomeGuyPrince" | lolcat

# Init
FILE="/tmp/out.$$"
GREP="/bin/grep"
#....
# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
# ...
clear
figlet -f digital  " Downloading Keyring " | lolcat
curl -L https://archive.kali.org/archive-key.asc | apt-key add
sleep 2
figlet -f digital  " Writing Sources.list " | lolcat
echo "deb http://kali.download/kali kali-rolling main contrib non-free" | sudo tee /etc/apt/sources.list
sleep 2
figlet -f digital  " Updating Source List " | lolcat
apt update -y
sleep 2 
figlet -f slant 'KALIAN' | lolcat && figlet -f digital  " Coded by CryptoKingYT" | lolcat
exit
